ec2_region: "{{ ec2_region_choice | default('us-east-1') }}"
ec2_name_tag: "{{ ec2_name_tag_choice | default('Ansible_Demo') }}"

ec2_web_port: "{{ ec2_web_port_choice | default(8080) }}"
iis_test_message: "{{ iis_test_message_choice | default('Configured Using Ansible') }}"
