---
- name: Create Security Group for {{ ec2_name_tag }} Linux WebServers
  ec2_group:
    name: "{{ ec2_name_tag }}_SG"
    description: "Security Group for {{ ec2_name_tag }} WebServers"
    region: "{{ ec2_region }}"
    vpc_id: "{{ aws_vpc_id }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: SSH

      - proto: tcp
        ports:
          - "{{ ec2_web_port }}"
        cidr_ip: 0.0.0.0/0
        rule_desc: HTTP_WEB
  register: created_sg

- set_stats:
    data:
      ec2_security_group: "{{ created_sg['group_id'] | default('') }}"
  when: created_sg['group_id'] is defined